global:
  name: consul
  enabled: false
  datacenter: consul-quickstart-1673532407320
  image: hashicorp/consul-enterprise:1.14.3-ent
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  tls:
    enabled: true
  enableConsulNamespaces: true
externalServers:
  enabled: true
  hosts: [consul-quickstart-1673532407320.consul.dc87d3cf-5e4d-4cde-858c-d1905cf5fdc4.aws.hashicorp.cloud]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: https://13F39DDD1D00F208051B062C96043FF0.sk1.eu-west-1.eks.amazonaws.com
server:
  enabled: false
connectInject:
  enabled: true
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
        ports:
          - port: 8080